[project]
name = "ai"
version = "0.1.0"
description = ""
authors = [
    {name = "\u001b[H"}
]
requires-python = ">=3.14"
dependencies = [
    "numpy (>=2.5.2,<3.0.0)",
    "ruff (>=0.16.5,<0.17.0)",
    "pytest (>=9.1.1,<10.0.0)",
    "ollama (>=0.6.2,<0.7.0)",
    "sentence-transformers (>=6.0.0,<7.0.0)"
]


[project.scripts]
vinrei = "vinrei.chat:main"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
